version: 2

models:
  - name: example_model
    description: "Staging model that filters GitHub repos to Python only"
    columns:
      - name: name
        description: "Repository name"
      - name: full_name
        description: "Full repository name (owner/repo)"
      - name: description
        description: "Repository description"
      - name: stars
        description: "Number of stars"
      - name: forks
        description: "Number of forks"
      - name: language
        description: "Primary programming language (Python)"
      - name: url
        description: "Repository URL"
      - name: created_at
        description: "Repository creation date"
      - name: updated_at
        description: "Last update date"
